### ISSUE TITLE
Difficulty in installing requirements

### ISSUE THREAD

**Issue by TharinduDR** [sheffieldnlp/deepQuest#12]
**Describe the bug**
I am trying to install deepQuest via source in a python 3.6+ environment. However, when I am installing the dependencies, I am having difficulty installing the dependency - cloud. 

**To Reproduce**
`git clone https://github.com/sheffieldnlp/deepQuest.git
cd deepQuest
conda install theano
pip install -r requirements.txt `

I am getting the following error 
`ERROR: Command errored out with exit status 1:
     command: /home/anaconda3/envs/sentence_classification_3.6/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ethkdc6v/cloud/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ethkdc6v/cloud/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-ethkdc6v/cloud/pip-egg-info
         cwd: /tmp/pip-install-ethkdc6v/cloud/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ethkdc6v/cloud/setup.py", line 23
        print 'using regular setup tools'
                                        ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print('using regular setup tools')?
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
`

**Desktop:**
 - OS - Ubuntu 18.04
- Python 3.6.10 & 3.7

Is the library compatible above python 3.6?

**Comment by fredblain** [comment]
Hi @TharinduDR, 
this version of the toolkit only supports Python 2.7.

**Comment by TharinduDR** [comment]
Hi @fredblain 
Thank you
