### ISSUE TITLE
bug for eval_word_qe

### ISSUE THREAD

**Issue by cocaer** [sheffieldnlp/deepQuest#3]
In evaluation.py,eval_word_qe should not be passed to  four parameters.
[problem](https://github.com/sheffieldnlp/deepQuest/blob/01529fbd75c7d059a20a1aef35b3817134f2f669/quest/keras_wrapper/extra/evaluation.py#L156)

**Comment by fredblain** [comment]
Hi @cocaer, could you provide us with more information regarding this pb? what data and its format are you using, steps to reproduce, etc. ? so we could better understand the origins of the pb.
Best,

**Comment by cocaer** [comment]
pb1:  [` final_scores = eval_word_qe(ref, pred_list[0], ds.vocabulary['word_qe'], 'Word')` ](https://github.com/sheffieldnlp/deepQuest/blob/01529fbd75c7d059a20a1aef35b3817134f2f669/quest/keras_wrapper/extra/evaluation.py#L156) be replaced with ` final_scores = eval_word_qe(ref, pred_list[0], ds.vocabulary['word_qe'])` . Because 'eval_word_ge' is defined as  `def eval_word_qe(gt_list, pred_list, vocab):`

pb2: how  to apply thie system to wmt18 word level beacuase the new data has  the new format, which introduces the 'tag' flag.
@fredblain

**Comment by cocaer** [comment]
By the way, It seems that deepQuest  put all train, dev, test data into a single Dataset_*.pkl. So If I want to   try other test data. What should i do?And does deepQuest support multi-gpu? 

Thanks a lot!

**Comment by julia-ive** [comment]
Hi @cocaer, thanks a lot for your feedback. I am fixing this WordQE issue in my commit as shown above. Testing on new data is implemented for the moment only for Sentence QE (see documentation: Tutorial-Scoring). The procedure is unfortunately not tested for WordQE yet (ongoing). For WMT2018 data, please filter tags (take only target tags, for example). And, no, we do not support multi-gpu for now. I am closing this issue. Feel free to contact me directly on my email for any other questions.
